{% set name = "uplot-python" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/uplot_python-{{ version }}.tar.gz
  sha256: 4f8f9e2abaf1dca28576e0a0a5bb7b06f1ca67be4dede88ca14a2f3d7fd92d54

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - flit-core >=2,<4
    - pip
  run:
    - python >={{ python_min }}
    - ipython >=8.0.1
    - msgpack-python >=1.0.4
    - numpy >=1.15.4

test:
  imports:
    - uplot
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/uplot-python
  summary: Python wrapper for Î¼Plot time series.
  dev_url: https://github.com/stephane-caron/uplot-python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - stephane-caron
